---
- name: Install deps on remote host
  hosts: sgx
  become: true
  gather_facts: false
  tasks:
    - wait_for_connection:

    - setup:

    - name: rustup installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust
    - name: install rust/cargo
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 172800 #two days
    - name: Add intel Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
        state: present

    - name: Add gramine Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://packages.gramineproject.io/gramine-keyring.gpg
        state: present

    - name: Add intel repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy main
        state: present

    - name: Add gramine repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.gramineproject.io/ jammy main
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: install libs
      become: true
      apt:
        allow_downgrades: yes
        pkg:
          - libsgx-dcap-ql
          - libsgx-dcap-default-qpl=1.16.100.2-jammy1
          - gramine
          - cmake
          - clang
    - name: check for SGX support
      command: is-sgx-available
      ignore_errors: true
      register: sgxstatus
    - name: print sgx support status
      ansible.builtin.debug:
        msg: SGX Status {{ sgxstatus }}
      when: sgxstatus is defined
    - name: clone notary server
      git:
        repo: https://github.com/maceip/sgx-tlsn-notary-server.git
        dest: /home/ubuntu/sgx-tlsn-notary-server
        clone: yes
        update: yes
    - name: make repo
      environment:
        SGX: "1"
        PATH: "/home/ubuntu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PATH }}"
      command: make
      args:
         chdir: /home/ubuntu/sgx-tlsn-notary-server
      register: makestatus
    - name: print make status
      ansible.builtin.debug:
        msg: Notary Build Status {{ makestatus }}
      when: makestatus is defined
